on:
  pull_request:
  push:
    branches: [master]

jobs:
  format-check:
    name: Check formatting with treefmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Run treefmt
        run: nix fmt
      - name: Fail on diff
        run: git diff --quiet || { echo "::error::Formatter changes detected." && exit 1; }
  flake-checker:
    name: Check overall Flake health
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Run flake-checker
        uses: DeterminateSystems/flake-checker-action@main
